spring:
  application:
    name: booking-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8203

flights:
  apiUrl: http://localhost:8202/flights
  credentials:
    username: admin
    password: is_a_lie
customers:
  apiUrl: http://localhost:8201/customers
  credentials:
    username: admin
    password: is_a_lie
